# Generates a Venn diagram to show similarity in gene hits between samples
# This program relies on hit files generated by "BL_compare.R"

# Function for generating Euler diagrams
# INPUT: any number of PAIRED dataset + name values
# e.g. create_euler(A,"apples",B,"bananas")
create_eulerr<- function(...){
  # Taking arbitrary-size input
  inputs <- list(...)
  
  # Splitting by expected paired input
  names <- inputs[seq_along(inputs) %% 2 == 0]
  gene_lists <- inputs[! (seq_along(inputs) %% 2 == 0)]
  
  # Large list of all genes with only one entry for each
  # This is the backbone of the logical matrix
  all_genes <- unique(c(unlist(gene_lists)))
  
  # Logical matrix w/ TRUE/FALSE by if a set contains a gene
  mat <- sapply(gene_lists, function(x) all_genes %in% x)
  
  # Creating nice names for the matrix
  # The columns are read into the plot as labels by eulerr
  colnames(mat) <- names
  rownames(mat) <- all_genes
  
  # Sanity check that everything worked
  print(head(mat))
  
  # Building eulerr's internal structure for the plot
  fit <- euler(mat, shape = "ellipse")
  
  # Plotting. Reference for the parameters:
  # https://cran.r-project.org/web/packages/eulerr/eulerr.pdf
  p <- plot(fit,
            quantities = TRUE,
            legend=TRUE
  )
  return(p)
}