get_dds = function (counts_filenames="./star_samples/count_matrix_noENSG",
                    meta_filename = "./star_samples/meta.csv",
                    group_name,
                    combined_categories=list(),
                    samples_exclude=c(),
                    design,
                    test_name,
                    test_contrast,
                    pca_group = c("condition","duration"),
                    pca_point_aes = aes(shape=condition),
                    pca_biplots = list(main = c("PC1", "PC2"))) {  # combined_categories is a list of c()'d column names.
  #   Each item in the list creates a new entry in the metadata passed to the DDS.
  #   Entries are named "combined_1", "combined_2", etc. in order of the list.
  #     ex: list(c("cell_type","condition","duration"))
  print(paste("Analyzing",group_name))
  
  dir.create(paste0("results/",group_name),showWarnings = FALSE)
  
  # Reading count matrix generated by featureCounts
  counts_paired <- read.csv(paste0(counts_filenames,"_paired.tsv"), sep = "\t")
  counts_paired <- counts_paired[-c(1:6)]
  counts <- read.csv(paste0(counts_filenames,"_single.tsv"), sep = "\t")
  rownames(counts) <- counts$Geneid
  counts <- counts[-c(1:6)]
  counts <- cbind(counts, counts_paired)
  
  
  # Getting sample names from their file names (this is hard-coded for now, a passsed regex parameter would be better)
  colnames(counts) <- colnames(counts) %>% str_replace("...5.sort.", "") %>% str_replace("_sorted.bam", "") %>% str_replace_all("\\.","-")
  
  if (length(samples_exclude) > 0){
    counts <- counts[-samples_exclude]
  }
  
  print(paste("Using samples:",colnames(counts)))
  
  # Preparing the metadata file by adding a combined field
  meta <- read.csv(meta_filename,header=TRUE)
  if (length(samples_exclude) > 0){
    meta <- meta[-samples_exclude,]
  }
  rownames(meta) <- meta$X
  meta <- meta[-c(1)]
  i<-0
  for (combined_category in combined_categories){
    i<-i+1
    meta[paste0("combined_",i)] <- apply(meta[,combined_category], 1, paste, collapse = "_")
  }
  
  # Export model matrix
  mm <-model.matrix(design, meta)
  write.csv(mm, file=paste0("results/",group_name,"/",group_name,"_model-matrix.csv"))
  
  print(paste("Exported model matrix of dimensions", dim(mm),"and rank", qr(mm)$rank))
  
  
  # The main dds and design definition
  dds <-DESeqDataSetFromMatrix(counts, meta, design)
  # refining data
  ddstrim <- dds[rowSums(counts(dds)) > 10,]
  ddstrim <- DESeq(ddstrim)
  
  write.csv(counts(object = ddstrim, normalized=TRUE), file=paste0("results/",group_name,"/",group_name,"_norm-count-matrix.csv"))
  
  
  # transform dds for pca analysis
  vsd_ddstrim <- assay(vst(ddstrim))
  pca_data <- pca(vsd_ddstrim, metadata = meta, removeVar = 0.1)
  {
    for (plot_name in names(pca_biplots)){
      biplot(pca_data,
             colby = "sample_group",
             shape = "condition",
             title = paste0(group_name," - VST - PCA - ",plot_name), 
             legendPosition = "right",
             x = pca_biplots[[plot_name]][1],
             y = pca_biplots[[plot_name]][2])
      ggsave(path = paste0("results/", group_name), filename=paste0("/",group_name,"_vst-PCA_",plot_name,".pdf"), width=8, height=8, create.dir = TRUE)
    }
  }
  {
    pairsplot(pca_data,
              colby = "sample_group",
              shape = "condition",
              title = paste0(group_name," - VST - PCA"))
    ggsave(path = paste0("results/", group_name), filename=paste0("/",group_name,"_vst-PCA-all.pdf"), width=8, height=8, create.dir = TRUE)
  }
  # testing effect of refinement
  dds_refinement_test(dds, ddstrim, group_name, test_name, test_contrast)
  
  return (ddstrim)
}


##### Generating some results to test the efficacy of our dds refinements
##### Generating some results to test the efficacy of our dds refinements
##### Generating some results to test the efficacy of our dds refinements
##### Generating some results to test the efficacy of our dds refinements
dds_refinement_test = function (dds_before, dds_after, group_name, test_name, test_contrast){
  dds_before <- DESeq(dds_before)
  res_before <- results(dds_before, contrast = test_contrast)
  
  res_after <- results(dds_after, contrast = test_contrast)
  res_after <- res_after[complete.cases(res_after),]#remove any rows with NA
  
  # p-value distribution before
  res_before %>% as.data.frame() %>%
    arrange(padj) %>%
    ggplot(aes(x=pvalue)) +
    geom_histogram(color = "white", bins = 50)
  ggsave(path = paste0("results/", group_name, "/"), filename=paste0(test_name, "_pval-hist_before.pdf"), width=6, height=4, create.dir = TRUE)
  
  # p-value distribution after
  res_after %>% as.data.frame() %>%
    arrange(padj) %>%
    ggplot(aes(x=pvalue)) +
    geom_histogram(color = "white", bins = 50)
  ggsave(path = paste0("results/", group_name, "/"), filename=paste0(test_name, "_pval-hist_after.pdf"), width=6, height=4, create.dir = TRUE)
}



get_results = function (dds, contrast, group_name, results_name){
  print(paste("Creating results for", results_name, "within group", group_name))
  res <- results(dds, contrast = contrast)
  res <- res[complete.cases(res),] #remove any rows with NA
  
  res_named <- as.data.frame(res) %>%
    tibble::rownames_to_column(var = "gene_name") %>%
    arrange(padj, abs(log2FoldChange))
  
  # res_named<-add_gene_name(res)
  res_named <- res_named[!res_named$gene_name %in% NA,]
  
  # ENSMBL IDs are more unique than gene names
  # In converting from IDs to names, we now have multiple entries for these genes
  # This line removes those genes
  res_named <- res_named[!duplicated(res_named$gene_name),]
  
  write.csv(res_named, file=paste0("results/",group_name,"/acidosis-vs-control_anyq_anyFC_",results_name,".csv"))
  write.csv(res_named[res_named$padj < cutoff_FDR,], file=paste0("results/",group_name,"/Acidosis-vs-control_q",cutoff_FDR,"_anyFC_",results_name,".csv"))
  return (res_named)
}